targets:
  $default:
    builders:
      shelf_dto|dto_builder:
        enabled: true
        generate_for:
            - lib/**/*_dto.dart
            - bin/**/*_dto.dart
            - example/**/*_dto.dart

builders:
  shelf_dto|dto_builder:
    import: "package:shelf_dto/src/dto_builder.dart"
    builder_factories: ["dtoBuilder"]
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
    build_extensions: {".dart": [".dto.dart"]}