name: shelf_dto
description: A simple dto builder for dart, use annotations and code gen to create simple and complete DTO for your project.
version: 0.1.2+1
repository: https://github.com/HeronWest/shelf_dto

environment:
  sdk: ^3.3.4

dependencies:
  build: ^2.4.1
  build_runner: ^2.4.9
  source_gen: ^1.5.0
  analyzer: ^6.4.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
