name: shelf_dto
description: A simple dto builder for dart.
version: 0.1.0
repository: https://github.com/HeronWest/shelf_dtos

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  build_runner: ^2.4.9
  source_gen: ^1.5.0
  analyzer: ^6.4.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
